// <auto-generated />
using System;
using FileTracert.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FileTracert.Data.Migrations
{
    [DbContext(typeof(FileTracertDbContext))]
    [Migration("20260903140421_AddDirectoryExclusionCauses")]
    partial class AddDirectoryExclusionCauses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("FileTracert.Data.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultExtensionFilter")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("DefaultExtensionFilter");

                    b.Property<string>("ExcludedPaths")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ExcludedPaths");

                    b.Property<int>("LogMaxRows")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(500000);

                    b.Property<int>("LogRetentionDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(14);

                    b.Property<string>("MinimumLogLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Information");

                    b.Property<int>("SpaceMarginPercent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("FileTracert.Data.Entities.DirectoryNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExcludedByPath")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExcludedByScan")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMaterialized")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaterializedPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PendingJobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PendingName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PendingParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PendingState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UsnFileRef")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VolumeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MaterializedPath");

                    b.HasIndex("ParentId");

                    b.HasIndex("PendingParentId");

                    b.HasIndex("VolumeId", "ParentId");

                    b.ToTable("Directories", (string)null);
                });

            modelBuilder.Entity("FileTracert.Data.Entities.ExtensionCategory", b =>
                {
                    b.Property<string>("Extension")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Extension");

                    b.ToTable("ExtensionCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Extension = "jpg",
                            Category = "Image"
                        },
                        new
                        {
                            Extension = "jpeg",
                            Category = "Image"
                        },
                        new
                        {
                            Extension = "png",
                            Category = "Image"
                        },
                        new
                        {
                            Extension = "gif",
                            Category = "Image"
                        },
                        new
                        {
                            Extension = "bmp",
                            Category = "Image"
                        },
                        new
                        {
                            Extension = "tiff",
                            Category = "Image"
                        },
                        new
                        {
                            Extension = "tif",
                            Category = "Image"
                        },
                        new
                        {
                            Extension = "webp",
                            Category = "Image"
                        },
                        new
                        {
                            Extension = "heic",
                            Category = "Image"
                        },
                        new
                        {
                            Extension = "heif",
                            Category = "Image"
                        },
                        new
                        {
                            Extension = "raw",
                            Category = "Image"
                        },
                        new
                        {
                            Extension = "cr2",
                            Category = "Image"
                        },
                        new
                        {
                            Extension = "cr3",
                            Category = "Image"
                        },
                        new
                        {
                            Extension = "nef",
                            Category = "Image"
                        },
                        new
                        {
                            Extension = "arw",
                            Category = "Image"
                        },
                        new
                        {
                            Extension = "dng",
                            Category = "Image"
                        },
                        new
                        {
                            Extension = "orf",
                            Category = "Image"
                        },
                        new
                        {
                            Extension = "raf",
                            Category = "Image"
                        },
                        new
                        {
                            Extension = "svg",
                            Category = "Image"
                        },
                        new
                        {
                            Extension = "mp4",
                            Category = "Video"
                        },
                        new
                        {
                            Extension = "mov",
                            Category = "Video"
                        },
                        new
                        {
                            Extension = "avi",
                            Category = "Video"
                        },
                        new
                        {
                            Extension = "mkv",
                            Category = "Video"
                        },
                        new
                        {
                            Extension = "wmv",
                            Category = "Video"
                        },
                        new
                        {
                            Extension = "flv",
                            Category = "Video"
                        },
                        new
                        {
                            Extension = "webm",
                            Category = "Video"
                        },
                        new
                        {
                            Extension = "m4v",
                            Category = "Video"
                        },
                        new
                        {
                            Extension = "mpg",
                            Category = "Video"
                        },
                        new
                        {
                            Extension = "mpeg",
                            Category = "Video"
                        },
                        new
                        {
                            Extension = "3gp",
                            Category = "Video"
                        },
                        new
                        {
                            Extension = "mts",
                            Category = "Video"
                        },
                        new
                        {
                            Extension = "m2ts",
                            Category = "Video"
                        },
                        new
                        {
                            Extension = "mp3",
                            Category = "Audio"
                        },
                        new
                        {
                            Extension = "wav",
                            Category = "Audio"
                        },
                        new
                        {
                            Extension = "flac",
                            Category = "Audio"
                        },
                        new
                        {
                            Extension = "aac",
                            Category = "Audio"
                        },
                        new
                        {
                            Extension = "ogg",
                            Category = "Audio"
                        },
                        new
                        {
                            Extension = "wma",
                            Category = "Audio"
                        },
                        new
                        {
                            Extension = "m4a",
                            Category = "Audio"
                        },
                        new
                        {
                            Extension = "aiff",
                            Category = "Audio"
                        },
                        new
                        {
                            Extension = "alac",
                            Category = "Audio"
                        },
                        new
                        {
                            Extension = "opus",
                            Category = "Audio"
                        },
                        new
                        {
                            Extension = "pdf",
                            Category = "Document"
                        },
                        new
                        {
                            Extension = "doc",
                            Category = "Document"
                        },
                        new
                        {
                            Extension = "docx",
                            Category = "Document"
                        },
                        new
                        {
                            Extension = "xls",
                            Category = "Document"
                        },
                        new
                        {
                            Extension = "xlsx",
                            Category = "Document"
                        },
                        new
                        {
                            Extension = "ppt",
                            Category = "Document"
                        },
                        new
                        {
                            Extension = "pptx",
                            Category = "Document"
                        },
                        new
                        {
                            Extension = "txt",
                            Category = "Document"
                        },
                        new
                        {
                            Extension = "rtf",
                            Category = "Document"
                        },
                        new
                        {
                            Extension = "odt",
                            Category = "Document"
                        },
                        new
                        {
                            Extension = "ods",
                            Category = "Document"
                        },
                        new
                        {
                            Extension = "odp",
                            Category = "Document"
                        },
                        new
                        {
                            Extension = "md",
                            Category = "Document"
                        },
                        new
                        {
                            Extension = "csv",
                            Category = "Document"
                        },
                        new
                        {
                            Extension = "epub",
                            Category = "Document"
                        },
                        new
                        {
                            Extension = "zip",
                            Category = "Archive"
                        },
                        new
                        {
                            Extension = "rar",
                            Category = "Archive"
                        },
                        new
                        {
                            Extension = "7z",
                            Category = "Archive"
                        },
                        new
                        {
                            Extension = "tar",
                            Category = "Archive"
                        },
                        new
                        {
                            Extension = "gz",
                            Category = "Archive"
                        },
                        new
                        {
                            Extension = "bz2",
                            Category = "Archive"
                        },
                        new
                        {
                            Extension = "xz",
                            Category = "Archive"
                        },
                        new
                        {
                            Extension = "iso",
                            Category = "Archive"
                        });
                });

            modelBuilder.Entity("FileTracert.Data.Entities.FileEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attributes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("RowCreatedUtc");

                    b.Property<int>("DirectoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExcludedByPath")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExcludedByRoot")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExcludedByScan")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExcludedByType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FileCreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedUtc");

                    b.Property<DateTime>("FileModifiedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("ModifiedUtc");

                    b.Property<string>("Hash")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIncluded")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMaterialized")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPresent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastIndexedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PendingDirectoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PendingJobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PendingName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuickHash")
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("RowUpdatedUtc");

                    b.Property<long?>("UsnFileRef")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VolumeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Extension");

                    b.HasIndex("FileModifiedUtc");

                    b.HasIndex("SizeBytes");

                    b.HasIndex("VolumeId", "DirectoryId");

                    b.HasIndex("VolumeId", "UsnFileRef")
                        .IsUnique()
                        .HasFilter("[UsnFileRef] IS NOT NULL");

                    b.HasIndex("PendingDirectoryId", "IsIncluded", "IsPresent", "IsMaterialized");

                    b.HasIndex("VolumeId", "IsIncluded", "IsPresent", "SizeBytes");

                    b.HasIndex("DirectoryId", "PendingDirectoryId", "IsIncluded", "IsPresent", "IsMaterialized");

                    b.ToTable("Files", (string)null);
                });

            modelBuilder.Entity("FileTracert.Data.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDismissed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VolumeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsDismissed", "IsRead", "TimestampUtc");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("FileTracert.Data.Entities.OperationJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlockReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("BytesProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DependsOnJobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstimateIsLive")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FreedBytesSource")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsIntraVolume")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RequiredBytesTarget")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceVolumeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetRelativePath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetVolumeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnJobId");

                    b.HasIndex("SequenceOrder")
                        .IsUnique();

                    b.HasIndex("SourceVolumeId");

                    b.HasIndex("TargetVolumeId");

                    b.ToTable("OperationJobs", (string)null);
                });

            modelBuilder.Entity("FileTracert.Data.Entities.OperationJobItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesCopied")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceRelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetRelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TempPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("JobId");

                    b.ToTable("OperationJobItems", (string)null);
                });

            modelBuilder.Entity("FileTracert.Data.Entities.SpaceLedgerEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("DeltaBytes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("VolumeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("VolumeId", "IsActive");

                    b.ToTable("SpaceLedgerEntries", (string)null);
                });

            modelBuilder.Entity("FileTracert.Data.Entities.Volume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CapacityBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileSystem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FreeBytesLastKnown")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCatalogable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRemovable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastDriveLetter")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastFullScanUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastUsn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhysicalDiskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanEngine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UsnJournalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VolumeGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsCatalogable");

                    b.HasIndex("VolumeGuid")
                        .IsUnique();

                    b.ToTable("Volumes", (string)null);
                });

            modelBuilder.Entity("FileTracert.Data.Entities.WatchedRoot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilterOverrideJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("VolumeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VolumeId");

                    b.ToTable("WatchedRoots", (string)null);
                });

            modelBuilder.Entity("FileTracert.Data.Entities.DirectoryNode", b =>
                {
                    b.HasOne("FileTracert.Data.Entities.DirectoryNode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FileTracert.Data.Entities.DirectoryNode", null)
                        .WithMany()
                        .HasForeignKey("PendingParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FileTracert.Data.Entities.Volume", "Volume")
                        .WithMany("Directories")
                        .HasForeignKey("VolumeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Volume");
                });

            modelBuilder.Entity("FileTracert.Data.Entities.FileEntry", b =>
                {
                    b.HasOne("FileTracert.Data.Entities.DirectoryNode", "Directory")
                        .WithMany("Files")
                        .HasForeignKey("DirectoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FileTracert.Data.Entities.DirectoryNode", null)
                        .WithMany()
                        .HasForeignKey("PendingDirectoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FileTracert.Data.Entities.Volume", "Volume")
                        .WithMany("Files")
                        .HasForeignKey("VolumeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Directory");

                    b.Navigation("Volume");
                });

            modelBuilder.Entity("FileTracert.Data.Entities.OperationJob", b =>
                {
                    b.HasOne("FileTracert.Data.Entities.OperationJob", "DependsOnJob")
                        .WithMany()
                        .HasForeignKey("DependsOnJobId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FileTracert.Data.Entities.Volume", "SourceVolume")
                        .WithMany()
                        .HasForeignKey("SourceVolumeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FileTracert.Data.Entities.Volume", "TargetVolume")
                        .WithMany()
                        .HasForeignKey("TargetVolumeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DependsOnJob");

                    b.Navigation("SourceVolume");

                    b.Navigation("TargetVolume");
                });

            modelBuilder.Entity("FileTracert.Data.Entities.OperationJobItem", b =>
                {
                    b.HasOne("FileTracert.Data.Entities.OperationJob", "Job")
                        .WithMany("Items")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("FileTracert.Data.Entities.SpaceLedgerEntry", b =>
                {
                    b.HasOne("FileTracert.Data.Entities.OperationJob", "Job")
                        .WithMany("LedgerEntries")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FileTracert.Data.Entities.Volume", "Volume")
                        .WithMany()
                        .HasForeignKey("VolumeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Volume");
                });

            modelBuilder.Entity("FileTracert.Data.Entities.WatchedRoot", b =>
                {
                    b.HasOne("FileTracert.Data.Entities.Volume", "Volume")
                        .WithMany("WatchedRoots")
                        .HasForeignKey("VolumeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Volume");
                });

            modelBuilder.Entity("FileTracert.Data.Entities.DirectoryNode", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("FileTracert.Data.Entities.OperationJob", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("LedgerEntries");
                });

            modelBuilder.Entity("FileTracert.Data.Entities.Volume", b =>
                {
                    b.Navigation("Directories");

                    b.Navigation("Files");

                    b.Navigation("WatchedRoots");
                });
#pragma warning restore 612, 618
        }
    }
}
