<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FileTracert.Contracts\FileTracert.Contracts.csproj" />
    <ProjectReference Include="..\FileTracert.Data\FileTracert.Data.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

</Project>
